# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qnpwi_9xAgFDv2icQuipC4sF4LbZAKQd
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

def rysuj_okraglego_mikolaja_matplotlib():
    """Generuje rysunek okrągłego Świętego Mikołaja z detalami."""

    fig, ax = plt.subplots(figsize=(7, 9))

    # Konfiguracja osi
    ax.set_xlim(-150, 150)
    ax.set_ylim(-150, 150)
    ax.axis('off')

    # --- 1. Tułów (Okrągły Brzuch) ---
    brzuch_kolo = patches.Circle((0, -30), 60, color='red', ec='black', lw=1.5)
    ax.add_patch(brzuch_kolo)

    # Pas
    pas_prostokat = patches.Rectangle((-60, -40), 120, 15, color='black', ec='black')
    ax.add_patch(pas_prostokat)

    # Klamra pasa
    klamra_prostokat = patches.Rectangle((-15, -38), 30, 10, color='gold', ec='black')
    ax.add_patch(klamra_prostokat)

    # --- 2. Głowa i Broda ---

    # Głowa
    glowa_kolo = patches.Circle((0, 70), 25, color='peachpuff', ec='black', lw=1.5)
    ax.add_patch(glowa_kolo)

    # Broda
    broda_trojkat = patches.Polygon([(-45, 60), (0, 0), (45, 60)], closed=True, color='white', ec='black', lw=1.5)
    ax.add_patch(broda_trojkat)

    # Oczy
    oko_lewe = patches.Circle((-10, 75), 3, color='black')
    ax.add_patch(oko_lewe)
    oko_prawe = patches.Circle((10, 75), 3, color='black')
    ax.add_patch(oko_prawe)

    # Usta
    ax.plot([-10, 10], [60, 60], color='black', lw=1)


    # --- 3. Czapka ---
    czapka_punkty = [(-20, 95), (0, 140), (20, 95)]
    czapka_trojkat = patches.Polygon(czapka_punkty, closed=True, color='red', ec='black', lw=1.5)
    ax.add_patch(czapka_trojkat)

    obszycie_czapki = patches.Rectangle((-30, 90), 60, 10, color='white', ec='black', lw=1.5)
    ax.add_patch(obszycie_czapki)

    pompon_kolo = patches.Circle((0, 140), 8, color='white', ec='black', lw=1.5)
    ax.add_patch(pompon_kolo)

    # --- 4. Ręce (Krytyczna sekcja błędu) ---

    # Lewa ręka (WERYFIKACJA NAWIASÓW)
    reka_lewa = patches.Rectangle((-100, -50), 40, 15, angle=10, color='red', ec='black', lw=1) # Wiersz 56 lub okolice
    ax.add_patch(reka_lewa)

    # Prawa ręka
    reka_prawa = patches.Rectangle((60, -50), 40, 15, angle=-10, color='red', ec='black', lw=1)
    ax.add_patch(reka_prawa)

    # --- 5. Nogi i Buty ---

    # Noga lewa
    noga_lewa = patches.Rectangle((-45, -125), 20, 25, color='red', ec='black')
    ax.add_patch(noga_lewa)
    # But lewy
    but_lewy = patches.Rectangle((-48, -135), 25, 10, color='black', ec='black')
    ax.add_patch(but_lewy)

    # Noga prawa
    noga_prawa = patches.Rectangle((25, -125), 20, 25, color='red', ec='black')
    ax.add_patch(noga_prawa)
    # But prawy
    but_prawy = patches.Rectangle((23, -135), 25, 10, color='black', ec='black')
    ax.add_patch(but_prawy)


    # --- 6. Rysowanie Prezentów ---
    prezent1_x, prezent1_y, prezent1_w, prezent1_h = 75, -100, 30, 40
    prezent1 = patches.Rectangle((prezent1_x, prezent1_y), prezent1_w, prezent1_h, color='red', ec='black', lw=1.5)
    ax.add_patch(prezent1)
    ax.plot([prezent1_x + 15, prezent1_x + 15], [prezent1_y, prezent1_y + prezent1_h], color='gold', lw=3)
    ax.plot([prezent1_x, prezent1_x + prezent1_w], [prezent1_y + 20, prezent1_y + 20], color='gold', lw=3)

    prezent2_x, prezent2_y, prezent2_w, prezent2_h = 110, -100, 30, 30
    prezent2 = patches.Rectangle((prezent2_x, prezent2_y), prezent2_w, prezent2_h, color='green', ec='black', lw=1.5)
    ax.add_patch(prezent2)
    ax.plot([prezent2_x + 15, prezent2_x + 15], [prezent2_y, prezent2_y + prezent2_h], color='white', lw=3)
    ax.plot([prezent2_x, prezent2_x + prezent2_w], [prezent2_y + 15, prezent2_y + 15], color='white', lw=3)

    # --- 7. Wyświetlenie ---
    plt.title("Okrągły Święty Mikołaj (Matplotlib)")
    plt.show()

if __name__ == "__main__":
    rysuj_okraglego_mikolaja_matplotlib()

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import streamlit as st # <-- NOWY IMPORT

def rysuj_okraglego_mikolaja_matplotlib():
    """Generuje rysunek okrągłego Świętego Mikołaja z detalami."""

    # Zamiast plt.subplots(figsize=(7, 9)) musimy użyć fig, ax = ...
    fig, ax = plt.subplots(figsize=(7, 9))

    # Konfiguracja osi
    ax.set_xlim(-150, 150)
    ax.set_ylim(-150, 150)
    ax.axis('off')

    # --- 1. Tułów (Okrągły Brzuch) ---
    brzuch_kolo = patches.Circle((0, -30), 60, color='red', ec='black', lw=1.5)
    ax.add_patch(brzuch_kolo)

    # Pas
    pas_prostokat = patches.Rectangle((-60, -40), 120, 15, color='black', ec='black')
    ax.add_patch(pas_prostokat)

    # Klamra pasa
    klamra_prostokat = patches.Rectangle((-15, -38), 30, 10, color='gold', ec='black')
    ax.add_patch(klamra_prostokat)

    # --- 2. Głowa i Broda (Bardziej Okrągła) ---

    # Głowa
    glowa_kolo = patches.Circle((0, 70), 25, color='peachpuff', ec='black', lw=1.5)
    ax.add_patch(glowa_kolo)

    # Broda (Użycie okrągłego łuku i trójkąta dla mniej kanciastego kształtu)
    # Wypełnienie trójkątem
    broda_wypelnienie = patches.Polygon([(-45, 55), (0, 0), (45, 55)], closed=True, color='white', ec='none', lw=0)
    ax.add_patch(broda_wypelnienie)
    # Zaokrąglony łuk brody
    broda_luk = patches.Arc((0, 20), 100, 100, angle=0, theta1=200, theta2=340, color='black', linewidth=1.5)
    ax.add_patch(broda_luk)
    # Białe futro pod brodą (aby ukryć ostry czubek)
    broda_biala_podstawa = patches.Rectangle((-45, 0), 90, 5, color='white', ec='black', lw=1.5)
    ax.add_patch(broda_biala_podstawa)

    # Nos (NOWY ELEMENT: Dodajmy okrągły nos)
    nos_kolo = patches.Circle((0, 55), 5, color='peachpuff', ec='black', lw=1)
    ax.add_patch(nos_kolo)

    # Oczy
    oko_lewe = patches.Circle((-10, 75), 3, color='black')
    ax.add_patch(oko_lewe)
    oko_prawe = patches.Circle((10, 75), 3, color='black')
    ax.add_patch(oko_prawe)

    # Usta
    ax.plot([-10, 10], [60, 60], color='black', lw=1)


    # --- 3. Czapka ---
    czapka_punkty = [(-20, 95), (0, 140), (20, 95)]
    czapka_trojkat = patches.Polygon(czapka_punkty, closed=True, color='red', ec='black', lw=1.5)
    ax.add_patch(czapka_trojkat)

    obszycie_czapki = patches.Rectangle((-30, 90), 60, 10, color='white', ec='black', lw=1.5)
    ax.add_patch(obszycie_czapki)

    pompon_kolo = patches.Circle((0, 140), 8, color='white', ec='black', lw=1.5)
    ax.add_patch(pompon_kolo)

    # --- 4. Ręce (Wyżej i Dłuższe - Zmodyfikowane współrzędne i kąty) ---

    # Lewa ręka (Przesunięta w górę i wydłużona)
    # Rozmiar: 60 długości, 15 szerokości; Nowy kąt
    reka_lewa = patches.Rectangle((-100, 30), 60, 15, angle=135, color='red', ec='black', lw=1) # Podniesiona
    ax.add_patch(reka_lewa)
    # Lewa dłoń (Rękawica)
    dlon_lewa = patches.Circle((-115, 10), 10, color='black', ec='black', lw=1)
    ax.add_patch(dlon_lewa)

    # Prawa ręka (Przesunięta w górę i wydłużona)
    # Rozmiar: 60 długości, 15 szerokości; Nowy kąt
    reka_prawa = patches.Rectangle((60, 30), 60, 15, angle=-135, color='red', ec='black', lw=1) # Podniesiona
    ax.add_patch(reka_prawa)
    # Prawa dłoń (Rękawica)
    dlon_prawa = patches.Circle((115, 10), 10, color='black', ec='black', lw=1)
    ax.add_patch(dlon_prawa)


    # --- 5. Nogi i Buty ---

    noga_lewa = patches.Rectangle((-45, -125), 20, 25, color='red', ec='black')
    ax.add_patch(noga_lewa)
    but_lewy = patches.Rectangle((-48, -135), 25, 10, color='black', ec='black')
    ax.add_patch(but_lewy)

    noga_prawa = patches.Rectangle((25, -125), 20, 25, color='red', ec='black')
    ax.add_patch(noga_prawa)
    but_prawy = patches.Rectangle((23, -135), 25, 10, color='black', ec='black')
    ax.add_patch(but_prawy)


    # --- 6. Rysowanie Prezentów ---
    prezent1_x, prezent1_y, prezent1_w, prezent1_h = 75, -100, 30, 40
    prezent1 = patches.Rectangle((prezent1_x, prezent1_y), prezent1_w, prezent1_h, color='red', ec='black', lw=1.5)
    ax.add_patch(prezent1)
    ax.plot([prezent1_x + 15, prezent1_x + 15], [prezent1_y, prezent1_y + prezent1_h], color='gold', lw=3)
    ax.plot([prezent1_x, prezent1_x + prezent1_w], [prezent1_y + 20, prezent1_y + 20], color='gold', lw=3)

    prezent2_x, prezent2_y, prezent2_w, prezent2_h = 110, -100, 30, 30
    prezent2 = patches.Rectangle((prezent2_x, prezent2_y), prezent2_w, prezent2_h, color='green', ec='black', lw=1.5)
    ax.add_patch(prezent2)
    ax.plot([prezent2_x + 15, prezent2_x + 15], [prezent2_y, prezent2_y + prezent2_h], color='white', lw=3)
    ax.plot([prezent2_x, prezent2_x + prezent2_w], [prezent2_y + 15, prezent2_y + 15], color='white', lw=3)

    # --- 7. Wyświetlenie ---
    st.title("🎅 Święty Mikołaj (Streamlit)") # NOWY ELEMENT STREAMLIT
    st.pyplot(fig) # <-- ZAMIENIA plt.show()


if __name__ == "__main__":
    rysuj_okraglego_mikolaja_matplotlib()